#!/usr/bin/env Rscript
# Functions for AA subtypes clustering

#### Utility ####
CLUSTER_COLS <- list('profile'=quo(A:Y), 'pca'=quo(PC1:PC20), 'pca2'=quo(PC2:PC20))
########

#### k-means ####
make_kmeans_clusters <- function(tbl, cols, n=3, min_size=1, ...){
  cols <- enquo(cols)
  
  mat <- tibble_to_matrix(tbl, !!cols)
  
  km <- kmeans(mat, centers = n, ...)
  
  tbl <- mutate(tbl, cluster = km$cluster) %>%
    select(cluster, everything())
  
  small_clusters <- count(tbl, cluster) %>%
    filter(n < min_size) %>%
    pull(cluster)
  
  tbl[tbl$cluster %in% small_clusters, 'cluster'] <- NA
  
  return(list(tbl=tbl, kmeans=km))
}
########

#### hclust clustering ####
make_hclust_clusters <- function(tbl, cols, h = NULL, k = NULL, min_size = 1, dist_method = 'euclidean', ...){
  cols <- enquo(cols)
  
  if (is.na(h)){
    h <- NULL
  }
  if (is.na(k)){
    k <- NULL
  }
  
  mat <- tibble_to_matrix(tbl, !!cols)
  hc <- hclust(dist(mat, method = dist_method), ...)
  clus <- cutree(hc, h = h, k = k)
  
  tbl <- mutate(tbl, cluster = clus) %>%
    select(cluster, everything())
  
  small_clusters <- count(tbl, cluster) %>%
    filter(n < min_size) %>%
    pull(cluster)
  
  tbl[tbl$cluster %in% small_clusters, 'cluster'] <- NA
  
  return(list(tbl = tbl, hclust = hc))
}

########

#### hdbscan clustering ####
make_hdbscan_clusters <- function(tbl, cols, dist_method = 'euclidean', minPts=10, ...){
  cols <- enquo(cols)
  
  mat <- tibble_to_matrix(tbl, !!cols)
  dis <- dist(mat, method = dist_method)
  hdb <- hdbscan(mat, minPts = minPts, xdist = dis, ...)
  
  tbl <- mutate(tbl, cluster = hdb$cluster) %>% 
    select(cluster, everything()) %>%
    mutate(cluster = na_if(cluster, 0))
  
  return(list(tbl = tbl, hdbscan = hdb))
}
########

#### dbscan clustering ####
make_dbscan_clusters <- function(tbl, cols, eps, dist_method = 'euclidean', minPts=5, ...){
  cols <- enquo(cols)
  
  mat <- tibble_to_matrix(tbl, !!cols)
  dis <- dist(mat, method = dist_method)
  db <- dbscan(dis, eps=eps, minPts = minPts, ...)
  
  tbl <- mutate(tbl, cluster = db$cluster) %>% 
    select(cluster, everything()) %>% 
    mutate(cluster = na_if(cluster, 0))
  
  return(list(tbl = tbl, hdbscan = db))
}
########

#### Cluster Analysis ####
# Wrapper function
# Expects tbl to be in the format generated by make_dms_wide in subtypes_utils.R
# TODO - overall profile for cluster
make_cluster_plots <- function(tbl, cols, chem_env_cols){
  cols <- enquo(cols)
  chem_env_cols <- enquo(chem_env_cols)
  n_clusters <- n_distinct(tbl$cluster)
  plots <- list()
  plots$tsne <- labeled_plot(plot_tsne_clusters(tbl), units='cm', height = 20, width = 20)
  plots$ramachanran_angles <- labeled_plot(plot_ramachandran_angles(tbl), units='cm', height = 20, width = 20)
  plots$cluster_sizes <- labeled_plot(plot_cluster_sizes(tbl), units='cm', height = 10, width = n_clusters*0.5 + 2, limitsize=FALSE)
  plots$mean_profiles <- labeled_plot(plot_cluster_profiles(tbl, !!cols), units='cm', height = n_clusters*0.5 + 2, width = 15, limitsize=FALSE)
  plots$profile_correlation <- labeled_plot(plot_cluster_profile_correlation(tbl, !!cols), units='cm', height = n_clusters*0.5 + 2, width = n_clusters*0.5 + 4, limitsize=FALSE)
  plots$foldx_profiles <- labeled_plot(plot_cluster_foldx_profiles(tbl), units='cm', height = n_clusters*0.5 + 2, width = 25, limitsize=FALSE)
  plots$chem_env_profiles <- labeled_plot(plot_cluster_chem_env_profiles(tbl, !!chem_env_cols), units='cm', height = n_clusters*0.5 + 2, width = 25, limitsize=FALSE)
  return(plots)
}

# All functions expect a cluster tibble
plot_tsne_clusters <- function(tbl){
  mutate(dms_wide, cluster_sym = str_sub(cluster, start = -1)) %>%
    ggplot(aes(x=tSNE1, y=tSNE2, colour=cluster_sym)) +
    geom_point() +
    facet_wrap(~wt) +
    scale_colour_brewer(type = 'qual', palette = 'Set3', na.value = 'grey') +
    guides(colour = guide_legend(title = 'Cluster'))
}

plot_ramachandran_angles <- function(tbl){
  tbl <- mutate(tbl, cluster_num = str_sub(cluster, start = -1))
  ggplot(tbl, aes(x=phi, y=psi, colour=cluster_num)) +
    geom_point() +
    facet_wrap(~wt) +
    scale_x_continuous(breaks = c(-180, -90, 0, 90, 180)) +
    scale_y_continuous(breaks = c(-180, -90, 0, 90, 180)) +
    scale_colour_viridis_d() +
    labs(x = expression(Phi), y = expression(Psi)) +
    guides(colour = guide_legend(title = 'Cluster')) +
    theme(panel.grid.major = element_line(linetype = 'dotted', colour='gray'))
}

plot_cluster_sizes <- function(tbl){
  size <- group_by(tbl, cluster) %>%
    tally() %>%
    mutate(aa = str_sub(cluster, end=1))
    
  ggplot(size, aes(x=cluster, y=n, fill=aa)) +
    geom_col() +
    scale_fill_manual(values = AA_COLOURS) +
    guides(fill=FALSE) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    labs(x='', y = 'Cluster Size')
}

cluster_mean_profiles <- function(tbl, cols){
  cols <- enquo(cols)
  group_by(tbl, cluster) %>%
    summarise_at(.vars = vars(A:Y), .funs = mean)
}

plot_cluster_profiles <- function(tbl, cols){
  cols <- enquo(cols)
  profiles <- cluster_mean_profiles(tbl, !!cols) %>%
    pivot_longer(-cluster, names_to = 'mut', values_to = 'score') %>%
    drop_na(cluster)
  
  ggplot(profiles, aes(x=mut, y=cluster, fill=score)) +
    geom_tile() +
    scale_fill_gradient2() +
    coord_fixed() +
    ggtitle('Cluster average profiles') +
    guides(fill=guide_colourbar(title = 'Normalised ER')) +
    theme(axis.ticks = element_blank(),
          panel.background = element_blank(),
          axis.title = element_blank(),
          axis.text.x = element_text(colour = AA_COLOURS[unique(profiles$mut)]),
          axis.text.y = element_text(colour = AA_COLOURS[str_sub(unique(profiles$cluster), end = 1)]))
}

cluster_profile_correlation <- function(tbl, cols){
  cols <- enquo(cols)
  cluster_mean_profiles(tbl, !!cols) %>%
    drop_na(cluster) %>%
    transpose_tibble(cluster, id_col = 'aa') %>%
    tibble_correlation(x=-aa) %>%
    rename(cluster1 = cat1, cluster2 = cat2) %>%
    mutate(wt1 = str_sub(cluster1, end = 1),
           wt2 = str_sub(cluster2, end = 1))
}

plot_cluster_profile_correlation <- function(tbl, cols){
  cols <- enquo(cols)
  cors <- cluster_profile_correlation(tbl, !!cols)
  
  ggplot(cors, aes(x=cluster1, y=cluster2, fill=cor)) +
    geom_tile() +
    scale_fill_gradient2() +
    ggtitle('Correlation between mean ER profiles') +
    coord_fixed() +
    theme(axis.ticks = element_blank(),
          panel.background = element_blank(),
          axis.title = element_blank(),
          axis.text.x = element_text(colour = AA_COLOURS[str_sub(levels(cors$cluster1), end = 1)], angle = 90, vjust = 0.5, hjust = 1),
          axis.text.y = element_text(colour = AA_COLOURS[str_sub(levels(cors$cluster2), end = 1)]))
}

cluster_foldx_profiles <- function(tbl){
    full_join(group_by(tbl, cluster) %>% summarise_at(vars(total_energy:energy_ionisation), mean, na.rm=TRUE),
              group_by(tbl, cluster) %>% summarise(n = n(), n_foldx = sum(!is.na(total_energy))),
              by = 'cluster')
    
}

plot_cluster_foldx_profiles <- function(tbl){
  profiles <- cluster_foldx_profiles(tbl) %>%
    pivot_longer(cols = total_energy:energy_ionisation, names_to = 'term', values_to = 'ddg') %>%
    group_by(term) %>%
    mutate(rel_ddg = ddg / max(abs(ddg), na.rm = TRUE)) %>%
    ungroup()
  
  # Group terms based on complete profiles only
  term_order <- group_by(profiles, cluster) %>%
    filter(all(!is.nan(rel_ddg))) %>%
    ungroup() %>%
    add_factor_order(cluster, term, rel_ddg) %>%
    pull(term) %>%
    levels()
  
  profiles <- mutate(profiles,
                     term = factor(term, levels = term_order),
                     cluster = factor(cluster),
                     prop = str_c(n_foldx, '/', n))
  
  cluster_labs <- levels(profiles$cluster)
  prop_labs <- structure(profiles$prop, names = as.character(profiles$cluster))[cluster_labs]
  
  ggplot(profiles,
         aes(x=term, y=as.numeric(cluster), fill=rel_ddg)) +
    geom_raster() +
    scale_fill_gradient2() +
    scale_y_continuous(breaks = 1:length(cluster_labs),
                       labels = cluster_labs,
                       sec.axis = sec_axis(~.,
                                           breaks = 1:length(prop_labs),
                                           labels = prop_labs)) +
    coord_fixed() +
    guides(fill = guide_colourbar(title = expression(frac(Delta*Delta*'G', 'max'['term']*'(|'*Delta*Delta*'G|)')))) + 
    theme(plot.title = element_text(hjust = 0.5, size=8),
          axis.ticks = element_blank(),
          panel.background = element_blank(),
          axis.title = element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
          axis.text.y.left = element_text(colour = AA_COLOURS[str_sub(unique(profiles$cluster), end = 1)]),
          legend.title.align = 0.5)
}

cluster_chem_env_profiles <- function(tbl, cols){
  cols <- enquo(cols)
  col_names <- colnames(select(tbl, !!cols))
  full_join(group_by(tbl, cluster) %>% summarise_at(vars(!!cols), mean, na.rm=TRUE),
            group_by(tbl, cluster) %>% summarise(n = n(), n_chem_env = sum(!is.na(.data[[col_names[1]]]))),
            by = 'cluster')
}

# Currently assumes profile columns correspond to AA counts, would need to be updated with a completely new chem env scheme
plot_cluster_chem_env_profiles <- function(tbl, cols){
  cols <- enquo(cols)
  profiles <- cluster_chem_env_profiles(tbl, !!cols) %>%
    pivot_longer(!!cols, names_to = 'aa', values_to = 'count') %>%
    group_by(aa) %>%
    mutate(rel_count = log2((count + min(count[count > 0], na.rm = TRUE)/10)/mean(count, na.rm=TRUE))) %>%
    ungroup() %>%
    mutate(prop = str_c(n_chem_env, '/', n),
           aa = str_sub(aa, start = -1))
  
  # Group terms based on complete profiles only
  aa_order <- group_by(profiles, cluster) %>%
    filter(all(!is.nan(rel_count))) %>%
    ungroup() %>%
    add_factor_order(cluster, aa, rel_count) %>%
    pull(aa) %>%
    levels()
  
  profiles <- mutate(profiles, cluster = factor(cluster), aa = factor(aa, levels = aa_order))
  
  cluster_labs <- levels(profiles$cluster)
  prop_labs <- structure(profiles$prop, names = as.character(profiles$cluster))[cluster_labs]
  
  scale_cols <- c('red', 'orange', 'white', 'blue', 'purple')
  max_val <- max(abs(profiles$rel_count), na.rm = TRUE)
  scale_points <- rescale01(c(-max_val, -max_val/2, 0, max_val/2, max_val))
  
  ggplot(profiles,
         aes(x=aa, y=as.numeric(cluster), fill=rel_count)) +
    geom_raster() +
    scale_fill_gradientn(colours = scale_cols, values = scale_points, limits = c(-max_val, max_val)) +
    scale_y_continuous(breaks = 1:length(cluster_labs),
                       labels = cluster_labs,
                       sec.axis = sec_axis(~.,
                                           breaks = 1:length(prop_labs),
                                           labels = prop_labs)) +
    coord_fixed() +
    guides(fill = guide_colourbar(title = expression('log'[2]*frac('count', 'mean(count)')))) + 
    theme(plot.title = element_text(hjust = 0.5, size=8),
          axis.ticks = element_blank(),
          panel.background = element_blank(),
          axis.title = element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0, colour = AA_COLOURS[levels(profiles$aa)]),
          axis.text.y.left = element_text(colour = AA_COLOURS[str_sub(unique(profiles$cluster), end = 1)]),
          legend.title.align = 0.5)
}

########